### ISSUE TITLE
Placing elements based on a list of points or another diagram

### ISSUE THREAD

**Issue by danoneata** [danoneata/chalk#13]
For the placement of the nodes, it might be useful to have a counterpart of the functions [`position`](https://hackage.haskell.org/package/diagrams-lib-1.4.5.1/docs/Diagrams-Combinators.html#v:position) or [`atPoints`](https://hackage.haskell.org/package/diagrams-lib-1.4.5.1/docs/Diagrams-Combinators.html#v:atPoints) from `diagrams`. These would allow to place node elements at a given location based on a list of coordinates or the points from a given diagram:
```python
nodes = [circle(0.3) + text(str(i), 0.2) for i in range(6)]
diagram = place_at_points(regular_polygon(6, 1).as_points(), nodes)
# or alternatively
diagram = regular_polygon(6, 1).place(nodes)
```
Doing the effective placement should be straightforward; the harder bit is to to get the "points" of a diagram.

**Comment by srush** [comment]
`position` would be great. AtPoints does seem harder, particularly if it is supposed to work with text and circles.

**Comment by srush** [comment]
This seems good now.
