### ISSUE TITLE
Grab the pip `chalk` name. 

### ISSUE THREAD

**Issue by srush** [danoneata/chalk#19]
I think this is pretty straightforward. Just need to upload to the chalk repo name.

**Comment by danoneata** [comment]
Do you have any details on how to do this? I've tried
```bash
python3 -m twine upload dist/*
```
but ran into
```
403 The user 'doneata' isn't allowed to upload to project 'chalk'. See https://pypi.org/help/#project-name for more information
```

**Comment by srush** [comment]
Oh no, I wonder if that means someone else claimed it or something.

**Comment by danoneata** [comment]
Yes, `chalk-diagrams` seems to work! I'll keep that for the time being. If you have a PyPI profile, I can add you to the list of maintainers. Unfortunately, I don't know of an easy way to add multiple authors to the `setup.py` file.
