### ISSUE TITLE
Inner styles in SVG are not getting overwritten

### ISSUE THREAD

**Issue by danoneata** [danoneata/chalk#22]
This code
```python
circle(1).fill_color(papaya).fill_color(black)
```
generates a black circle when rendered as PNG and a papaya one when rendered as SVG. The expected behaviour should be the former. The generated SVG code seems correct:
```
<g style="fill: #000000;"><g style="fill: #ff9700;"><g style=";" transform="scale(1)"><circle cx="0" cy="0" r="1" /></g></g></g>
```
Should we resolve the styling prior to rendering? Or is there a simpler solution?

**Comment by srush** [comment]
I think the best way to handle this is to pass a chalk `Style` object to `render_svg` in a similar way as `Transform` is passed to `get_bounding_box`. Each subclass can then know the global style state.
