### ISSUE TITLE
Please add a `LICENSE` file in the repository as well as in the PyPI source

### ISSUE THREAD

**Issue by sugatoray** [danoneata/chalk#26]
Please add a `LICENSE` file in the repository as well as in the PyPI source.

:point_right: I am working on adding `chalk-diagrams` to conda-forge. A license file is necessary in the PyPI source. Here's the PR.

- https://github.com/conda-forge/staged-recipes/pull/19013

:zap: Once the library is added to conda-forge, it could be installed with `conda`.

```sh
conda install -c conda-forge chalk-diagrams
```

**Comment by sugatoray** [comment]
cc: @danoneata

**Comment by srush** [comment]
@danoneata I normally just default to MIT ? Does that work with you.

**Comment by danoneata** [comment]
Yes, MIT works for me as well. I can add it later today, if it's not a hurry

**Comment by danoneata** [comment]
Done; I've added the license to both the repo and [PyPI](https://pypi.org/project/chalk-diagrams/). @sugatoray let me know if it's all good.
