### ISSUE TITLE
Better Text bounding boxes

### ISSUE THREAD

**Issue by srush** [danoneata/chalk#69]
For text bounding boxes we are reliant on calling PyCairo TextExtents. As far as I can tell this function call is just broken, or something else is going wrong:

![image](https://user-images.githubusercontent.com/35882/174086638-5aaeaab2-05e7-4f11-a3f4-437fa51499f2.png)

One solution is that if we know the exact font there are ways of calculating sizes. However this might rely on having a font distributed with the library.

**Comment by danoneata** [comment]
Yup! I agree!
