### ISSUE TITLE
`Planar` install issue. 

### ISSUE THREAD

**Issue by srush** [danoneata/chalk#84]
It seems like planar relies on a conversion library 'build_py_2to3' that is deprecated in the latest versions of distutils. This is a note to myself to fix this. 

I think the best way to do this may be to just host a modern version of this code. My fault for using an old library.

@renhaofan

I try to run command pip install git+https://github.com/danoneata/chalk@srush-patch-1, But an error occurred:

 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-ofq9w8yg/planar_3384c07b07cb49e694e3d9f59655d633/setup.py", line 11, in <module>
          from distutils.command.build_py import build_py_2to3 as build_py
      ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py' (/home/steve/.conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/command/build_py.py)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ofq9w8yg/planar_3384c07b07cb49e694e3d9f59655d633/setup.py", line 14, in <module>
          raise ImportError("build_py_2to3 not found in distutils - it is required for Python 3.x")
      ImportError: build_py_2to3 not found in distutils - it is required for Python 3.x
      [end of output]
And my python version is totally the same with Colab.

>>> sys.version
'3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]'

**Comment by pawamoy** [comment]
Sorry for necro-bumping, but I experience this very issue today still, see https://github.com/chalk-diagrams/planar/issues/1. I'm not sure to understand if this was fixed but not released, or not fixed at all.
